### ISSUE TITLE
Memory model

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#122]
- [ ]    IsParent(BorrowNode, BorrowEdge),
- [ ]    WriteBack(BorrowNode, BorrowEdge),
- [ ]    UnpackRef,
- [ ]    PackRef,
- [ ]    UnpackRefDeep,
- [ ]    PackRefDeep,

**Comment by nvjle** [comment]
These are generated for the Move Prover, we can ignore them in the translation (nop translation). This is also what the Move-to-EVM compiler does.
See, e.g., `move-prover/bytecode/src/spec_instrumentation.rs`, the paper at `move-prover/doc/paper21/main.pdf`, etc.
