### ISSUE TITLE
Builtins

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#123]
- [ ] Uninit,
- [x] Destroy,
- [x]     ReadRef,
- [x]     WriteRef,
- [x]     FreezeRef,
- [ ]     Havoc(HavocKind),
- [ ]     Stop,

**Comment by nvjle** [comment]
Uninit, Havoc, and Stop are generated for the Move Prover, we can ignore them in the translation (nop translation). This is also what the Move-to-EVM compiler does.
See, e.g., `move-prover/bytecode/src/spec_instrumentation.rs`, the paper at `move-prover/doc/paper21/main.pdf`, etc.

The others in the list that do need translation are already done.
