### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#124]
- [ ]    TraceLocal(TempIndex),
- [ ]    TraceReturn(usize),
- [ ]    TraceAbort,
- [ ]    TraceExp(TraceKind, NodeId),
- [ ]    TraceGlobalMem(QualifiedInstId<StructId>),

**Comment by nvjle** [comment]
These are generated for the Move Prover, we can ignore them in the translation (nop translation). This is also what the Move-to-EVM compiler does.
See, e.g., `move-prover/bytecode/src/spec_instrumentation.rs`, the paper at `move-prover/doc/paper21/main.pdf`, etc.
