### ISSUE TITLE
Opaque Call Markers

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#126]
- [ ] OpaqueCallBegin(ModuleId, FunId, Vec<Type>)
- [ ] OpaqueCallEnd(ModuleId, FunId, Vec<Type>)

**Comment by nvjle** [comment]
These are generated for the Move Prover, we can ignore them in the translation (nop translation). This is also what the Move-to-EVM compiler does.
See, e.g., `move-prover/bytecode/src/spec_instrumentation.rs`, the paper at `move-prover/doc/paper21/main.pdf`, etc.
