### ISSUE TITLE
[Bug] Test harness should be able to process different file types and pass .mv file to the compiler.

### ISSUE THREAD

**Issue by aditya-solana** [solana-labs/move#14]
# 🐛 Bug
We have .move, .mvir, and .mv files. The test harness should be able to invoke the right tools for each of these and invoke the compiler with the .mv files.

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by brson** [comment]
Done.
