### ISSUE TITLE
move stackless bytecode integration

### ISSUE THREAD

**Issue by aditya-solana** [solana-labs/move#21]
- [ ] Scaffolding to use stackless bytecode as starting point for lowering to llvm-ir
  - [ ] Interface to llvm context
  - [ ] Abstraction for llvm module 
  - [ ] Lower function declaration and return type
- [ ] Write llvm-ir to file
- [ ] Documentation of command line interface
- [ ] Test harness

**Comment by aditya-solana** [comment]
https://github.com/brson/move/commit/7f21c3f7c431cb1124f7155c95c31a53229a8166

**Comment by brson** [comment]
Done. ir-tests, move-ir-tests, and rbpf-tests all use the stackless bytecode translation.
