### ISSUE TITLE
[Bug] move-native is not formatted correctly

### ISSUE THREAD

**Issue by brson** [solana-labs/move#237]
It's not part of the workspace and doesn't end up examined by `cargo xfmt`.

Reformat it and add the correct command to CI.

**Comment by nvjle** [comment]
Will xlint and xclippy also run?

**Comment by brson** [comment]
xlint already seems to run against it, probably because it is a custom program that ignores the workspace.

We can also run clippy on it in CI.

I don't know offhand how to run xfmt and xclippy on it - i was just thinking of running regular `cargo fmt`, but I'll look into what it would take to run the custom ones.

I know adding it to the workspace has been difficult in the past because being a cdylib causes some strange problems, but I have an idea of how it might be added to the workspace by not declaring it a cdylib (but still compiling it as one for production and tests).
