### ISSUE TITLE
Run ci both on mac and linux

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#252]
The compiler should have clean runs on both Linux and mac as we will be supporting these two platforms.

**Comment by yihau** [comment]
it means we want to test this one https://github.com/solana-labs/move/blob/813fefa582f56673e83f1d71ff409ad10e11ff9a/.github/workflows/llvm-ci-pre-land.yml#L69-L94 in mac as well correct?

**Comment by dmakarov** [comment]
Unit tests should run on macos as well, yes.
