### ISSUE TITLE
[Bug] The Discord invite link in the "Questions/Help issue template isn't working

### ISSUE THREAD

**Issue by bernieblume** [solana-labs/move#306]
# 🐛 Bug

The Discord invite link in the "Questions/Help issue template isn't working

## To reproduce

Create new issue in github. Choose the template Questions/Help (1 of 4 templates).

The template will say the issue will be closed, go to Discord instead. But the Discord  link provided isn't working.

**Stack trace/error message**
```
Invite Invalid. This invite might be expired, or you might not have permission to join.
```

## Expected Behavior

I should be able to join the Discord server.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by ksolana** [comment]
solana's #proj-move is public https://discord.com/channels/428295358100013066/1022546078811291708
