### ISSUE TITLE
[Bug] Handle mutexes and probably atomics

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#320]
See: [aptos-move/move-examples/defi/sources/locked_coins.move](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/defi/sources/locked_coins.move)

EBPF documentation on atomics: https://www.kernel.org/doc/html/latest/bpf/instruction-set.html#atomic-operations

**Comment by brson** [comment]
I think that the locks in the referenced example are not machine-level locks, but instead logical locks on when and who are allowed to withdraw funds from a contract.

As far as I know, any machine-level concurrency between move transactions are handled in a way similar to solana - by analyzing the data dependencies between them and executing them in an order that does not produce concurrent mutations.

Move code will probably not need atomics.

**Comment by ksolana** [comment]
not required.
