### ISSUE TITLE
[PR commands] check-pre-merge

### ISSUE THREAD

**Issue by yihau** [solana-labs/move#358]
@check-pre-merge: run all the pre-merge checks. Essentially run all the checks we run already. This is useful if we want to rerun all the checks without updating the patch.

**Comment by yihau** [comment]
not sure when do you re-run a successful job but we can do it via a UI button, `Re-run all jobs`

![Screenshot 2023-09-11 at 3 32 58 PM](https://github.com/solana-labs/move/assets/8209234/f8cdce85-cffa-4584-a5e5-3456833edcf7)

do we still need the command?

**Comment by ksolana** [comment]
LGTM.

**Comment by yihau** [comment]
okay. let's use the UI solution for a while. if we still feel bad, we can reopen this one!
