### ISSUE TITLE
[PR commands] rebase

### ISSUE THREAD

**Issue by yihau** [solana-labs/move#361]
Rebase the patch on top of main. This would also trigger all the tests upon successful rebase. I think github already has this feature but i'm not sure why it doesn't show up already. see: https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

**Comment by yihau** [comment]
just set up the feature.

![Screenshot 2023-09-11 at 3 10 22 PM](https://github.com/solana-labs/move/assets/8209234/84a0e901-bcec-4f72-bb48-69bdc1f0ef6f)

you can see the button in a PR now. you can check with this PR https://github.com/solana-labs/move/pull/356

**Comment by ksolana** [comment]
working, i see. Thanks so much!

**Comment by ksolana** [comment]
!help
