### ISSUE TITLE
[Bug] Support primitive types listed in move_model::ty::PrimitiveType

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#47]
From move_model::ty::PrimitiveType
https://github.com/move-language/move/blob/main/language/move-model/src/ty.rs#L49

- [x] Bool
- [x] U8
- [x] U32
- [x] U64
- [x] U128
- [x] U256
- [x] Address
- [x] Signer

**Comment by nvjle** [comment]
I have removed Num, Range, and EventStore as those only apply to specs (i.e., same as we discussed in meeting today about issues 122, 123, 124, 125).
