### ISSUE TITLE
[Bug] cargo build in `tools/move-mv-llvm-compiler` directory should also build move-ir-compiler

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#50]
Since it is not built currently, `cargo test` fails for the tests requiring `move-ir-compiler`.

**Comment by brson** [comment]
If somebody wants to implement this, there is a pattern they can follow in the rbpf-tests harness using Once to do a one-time build of move-native. Something similar could be done for move-ir-compiler and move-compiler, though the cargo invocation needs to be a lot different - the rbpf-tests build is using the cargo from sbf-tools and building into its own target directory, whereas a build of move-ir-compiler and move-build needs to use the active toolchain and the default target directory.
