### ISSUE TITLE
shr is logical or arithmetic?

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#69]
Need to know before lowering these.

https://llvm.org/docs/LangRef.html#lshr-instruction

**Comment by nvjle** [comment]
The `shr` operation appears to be logical:
The interpreter invokes `shr_checked` here: https://github.com/solana-labs/move/blob/469a6be033b394c8281305fc74879b14360c652c/language/move-vm/runtime/src/interpreter.rs#L1960

Where` shr_checked` uses the ordinary Rust `>>`operator on Move's unsigned types:
https://github.com/solana-labs/move/blob/469a6be033b394c8281305fc74879b14360c652c/language/move-vm/types/src/values/values_impl.rs#L1616

According to the Rust reference for operator `>>`: "Arithmetic right shift on signed integer types, logical right shift on unsigned integer types":
https://doc.rust-lang.org/reference/expressions/operator-expr.html#arithmetic-and-logical-binary-operators
