### ISSUE TITLE
[test] Add ==, and != tests for all types u32, u64, u128, u256

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#70]
In file: [language/tools/move-mv-llvm-compiler/tests/move-ir-tests/eq.move](https://github.com/solana-labs/move/blob/llvm-sys/language/tools/move-mv-llvm-compiler/tests/move-ir-tests/eq.move)

**Comment by dmakarov** [comment]
These tests are now generated by our testgen tool. Although they're to be checked by running rbpf vm, not by validating generated llvm code. If they look good, we can add them to the repository and close this issue.

**Comment by ksolana** [comment]
Yeah, looks like this has been addressed by @dmakarov's patch. Thanks for working on it.
