### ISSUE TITLE
[Bug] Write a move test-generator to test codegen

### ISSUE THREAD

**Issue by ksolana** [solana-labs/move#84]
As you can see in #83, some off the codegen tests are fairly regular. We need to test all combinations but it is tedious to write them manually. Having a code-generator that output tests based on some template code. e.g., see [mustache](http://mustache.github.io/) for example. We can have our own little code-generator if that is simple.

**Comment by dmakarov** [comment]
I've been thinking/playing with this issue. I started with a Mustache template for cast tests, parameterizing variable parts of the test cases. I don't have a clear idea of a good general DSL for specifying test case templates and parameters for them. So some ideas would be much appreciated.

**Comment by ksolana** [comment]
We could totally roll out our own in rust. The advantage would be that we can 'import' existing libraries to generate valid test cases. In fact it will be much preferable if we do it in rust within the existing repo. This can also scale up to a 'bugpoint + creduce' like tool because we'll have the ability to invoke type checker to validate correct programs.

I shared the link to mustache just to show that this is possible.

**Comment by ksolana** [comment]
Maybe start with a simple function and parameterize over
- args
- return types
- And single statement of kind (a op b)

**Comment by dmakarov** [comment]
Mustache is quite useful. In fact I started with Mustache and it’s simple to use. I’ll make a WIP PR to begin with something and maybe cooperatively we’ll iterate to a useful tool.

**Comment by ksolana** [comment]
Found https://docs.rs/bart/latest/bart/ same as mustache. I have never used this but worth a try?
