### ISSUE TITLE
Cargo test for move-mv-llvm-compiler unit tests

### ISSUE THREAD

**Issue by aditya-solana** [solana-labs/move#9]
Running cargo test in move/language/tools/move-mv-llvm-compiler should do the following
For each .mvir file in move/language/tools/move-mv-llvm-compiler/tests
- [ ] Generate move bytecode from move-ir (move-ir-compiler -m a.mvir)
- [ ] Generate bitcode file from move ($MOVE_HOME/target/debug/move-mv-llvm-compiler -b a.mv)
- [ ] Add assertions as applicable (e.g., assert(FunctionName == "my_fun")
- [ ] Print cargo test stats

**Comment by brson** [comment]
@aditya-solana I have written a move-mv-llvm-compiler test harness:

https://github.com/brson/move/blob/llvm-test-harness/language/tools/move-mv-llvm-compiler/tests/ir-tests.rs

It doesn't work exactly as you suggest though.

It is based on converting MVIR to LLVM IR and comparing the result with a reference file, similar to parts of the LLVM and Rust test suite.

It uses the datatest_stable crate, as do most of the other move tests.

It

- creates a test for every .mvir in the testdata dir
- converts the mvir to mv bytecode with move-ir-compiler
- converts mv bytecode to llvm ir with move-mv-llvm-compiler
- names the llvm ir `${testname}.actual.ll` and compares it to `${testname}.expected.ll`
- if the two are different, errors and prints a diff

Actual test results can be promoted to expected test results. The mechanism I wrote to do this is by setting `PROMOTE_LLVM_IR`, which when set will cause the test harness to copy the `.actual.ll` files to `.expected.ll`. This mechanism could be changed to better match other parts of the move test suite. I haven't looked at it closely.

The `.expected.ll` files are checked into git.

Let me know what you think.

**Comment by brson** [comment]
Run with `cargo test -p move-mv-llvm-compiler --test ir-tests`

**Comment by brson** [comment]
Hm, currently it requires running `cargo build -p move-ir-compiler` first. It does not automatically build it.

**Comment by brson** [comment]
At the moment move-mv-llvm-compiler does not produce LLVM output, so this test suite isn't useful yet.

**Comment by brson** [comment]
This is done. Refinements to the ir-tests can be opened as new issues.
