### ISSUE TITLE
About vector implementation.

### ISSUE THREAD

**Issue by yuyang-ok** [solana-labs/move#96]
~~~
#[repr(C)]
#[derive(Debug)]
pub struct MoveUntypedVector {
    pub ptr: *mut u8,  // Safety: must be correctly aligned per type
    pub capacity: u64, // in typed elements, not u8
    pub length: u64,   // in typed elements, not u8
}

~~~
This maybe  inappropriate to ask.
What if this struct `MoveUntypedVector` add a field like `type_length` will make move `vector<T>` implemented more simpler.

like `push_back`
~~~
pub unsafe extern "C" fn push_back(
    type_ve: &MoveType,  // no need now  
    v: &mut MoveUntypedVector,
    e: *mut AnyValue
) {
   // you just copy `type_length` of data from `e` to `v`.
}
~~~

the only place you need `type_ve` is `Drop`??

**Comment by yuyang-ok** [comment]
>  I no longer recall why Rust does it that way, but there were probably good reasons; 
@brson thanks. the code looks a little tedious to me.

**Comment by brson** [comment]
It is pretty ugly code agreed!
